export const CARTE_ENTREPOT_DEPOT: Record<string, string> = {
    'Aix Matin': 'AIX',
    'Aix Soir': 'AIX',
    'Carrefour Antibes St Claude 0021': 'Magasin',
    'Carrefour Athis Mons 0503': 'Magasin',
    'Carrefour Drancy 0088': 'Magasin',
    'Carrefour Ivry Sur Seine 0032': 'Magasin',
    'Carrefour L Haÿ Les Roses 7330': 'Magasin',
    'Carrefour Market Antibes 7827': 'Magasin',
    'Carrefour Market Croissy sur seine 7854': 'Magasin',
    'Carrefour Market Marly le roi 7794': 'Magasin',
    'Carrefour Market Montpellier Justice 8000': 'Magasin',
    'Carrefour Market Nice Mont Boron 7886': 'Magasin',
    'Carrefour Market Saint André De La Roche 7633XX': 'Magasin',
    'Carrefour Market Versailles 7920': 'Magasin',
    'Carrefour Market Villeneuve Les Avignon 7603XX': 'Magasin',
    'Carrefour Monaco 0087': 'Magasin',
    'Carrefour Nice Lingostière 0029XX': 'Magasin',
    'Carrefour Pontault Combault 0081': 'Magasin',
    'Carrefour Rosny 0523': 'Magasin',
    'Carrefour Villejuif 7360': 'Magasin',
    'Castries J pour J': 'Castries',
    'Castries Matin': 'Castries',
    'Castries Midi': 'Castries',
    'Castries Soir': 'Castries',
    'Castries Zone Nîmes Matin': 'Castries',
    'Castries Zone Nîmes Midi': 'Castries',
    'Castries Zone Nîmes Soir': 'Castries',
    'F - Carrefour Nice TNL 0519': 'Magasin',
    'LEX -Carrefour Market Croissy sur seine 7854 - LEX': 'Magasin',
    'Rungis Zone1 Après Midi': 'Rungis',
    'Rungis Zone1 Matin': 'Rungis',
    'Rungis Zone1 Soir': 'Rungis',
    'Rungis Zone2 Après Midi': 'Rungis',
    'Rungis Zone2 J pour J': 'Rungis',
    'Rungis Zone2 Matin': 'Rungis',
    'Rungis Zone3 Après Midi': 'Rungis',
    'Rungis Zone3 J pour J': 'Rungis',
    'Rungis Zone3 Matin': 'Rungis',
    'Solo Antibes Laugier J pour J': 'Antibes',
    'Solo Antibes Laugier Matin': 'Antibes',
    'Solo Antibes Laugier Matin Monaco': 'Antibes',
    'Solo Antibes Laugier Midi': 'Antibes',
    'Solo Antibes Laugier Soir': 'Antibes',
    'Solo Antibes Laugier Soir Monaco': 'Antibes',
    'Villeneuve-la-Garenne Après Midi': 'VLG',
    'Villeneuve-la-Garenne J pour J': 'VLG',
    'Villeneuve-la-Garenne Matin': 'VLG',
    'Villeneuve-la-Garenne Soir': 'VLG',
    'Vitry Banlieue Matin': 'Vitry',
    'Vitry J pour J': 'Vitry',
    'Vitry Paris Après-Midi': 'Vitry',
    'Vitry Paris Matin': 'Vitry',
    'Vitry Soir': 'Vitry',
    'Vitry Paris Dimanche': 'Vitry'
};

export const TRANSPORTEURS = [
    { nom: 'BC one', suffixes: ['3'] },
    { nom: 'DUB', suffixes: ['0'] },
    { nom: 'GPC', suffixes: ['8'] },
    { nom: 'GPL', suffixes: ['7'] },
    { nom: 'RK', suffixes: ['6'] },
    { nom: 'Express', suffixes: ['2'] },
    { nom: 'MLG', suffixes: ['5'] },
    { nom: 'ID LOGISTICS', suffixes: [] },
    { nom: 'Sous traitants', suffixes: [] },
];
